# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: earth_mars.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='earth_mars.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x65\x61rth_mars.proto\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\r\x12\r\n\x05month\x18\x02 \x01(\r\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\r\"y\n\tAstronaut\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\rhealth_status\x18\x02 \x01(\x0e\x32\x17.Astronaut.HealthStatus\".\n\x0cHealthStatus\x12\x08\n\x04GOOD\x10\x00\x12\n\n\x06\x41ILING\x10\x01\x12\x08\n\x04\x44\x45\x41\x44\x10\x02\"T\n\x0cRescueDemand\x12\n\n\x02id\x18\x01 \x01(\r\x12\x19\n\nask_before\x18\x02 \x01(\x0b\x32\x05.Date\x12\x1d\n\tastronaut\x18\x03 \x03(\x0b\x32\n.Astronaut\"r\n\tRescueAck\x12\n\n\x02id\x18\x01 \x01(\r\x12*\n\x06\x63hoice\x18\x02 \x01(\x0e\x32\x1a.RescueAck.RescueAckChoice\"-\n\x0fRescueAckChoice\x12\x0c\n\x08REJECTED\x10\x00\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x01\"\\\n\x08\x46romMars\x12&\n\rrescue_demand\x18\x01 \x01(\x0b\x32\r.RescueDemandH\x00\x12 \n\nrescue_ack\x18\x02 \x01(\x0b\x32\n.RescueAckH\x00\x42\x06\n\x04type\"A\n\x0bRescueOffer\x12\n\n\x02id\x18\x01 \x01(\r\x12\x13\n\x04\x64\x61te\x18\x02 \x01(\x0b\x32\x05.Date\x12\x11\n\tnb_places\x18\x03 \x01(\r\"9\n\tFromEarth\x12$\n\x0crescue_offer\x18\x01 \x01(\x0b\x32\x0c.RescueOfferH\x00\x42\x06\n\x04typeb\x06proto3')
)



_ASTRONAUT_HEALTHSTATUS = _descriptor.EnumDescriptor(
  name='HealthStatus',
  full_name='Astronaut.HealthStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GOOD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AILING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEAD', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=145,
  serialized_end=191,
)
_sym_db.RegisterEnumDescriptor(_ASTRONAUT_HEALTHSTATUS)

_RESCUEACK_RESCUEACKCHOICE = _descriptor.EnumDescriptor(
  name='RescueAckChoice',
  full_name='RescueAck.RescueAckChoice',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REJECTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCEPTED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=348,
  serialized_end=393,
)
_sym_db.RegisterEnumDescriptor(_RESCUEACK_RESCUEACKCHOICE)


_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='Date.year', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='Date.month', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='day', full_name='Date.day', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=68,
)


_ASTRONAUT = _descriptor.Descriptor(
  name='Astronaut',
  full_name='Astronaut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Astronaut.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='health_status', full_name='Astronaut.health_status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ASTRONAUT_HEALTHSTATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=191,
)


_RESCUEDEMAND = _descriptor.Descriptor(
  name='RescueDemand',
  full_name='RescueDemand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RescueDemand.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ask_before', full_name='RescueDemand.ask_before', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='astronaut', full_name='RescueDemand.astronaut', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=277,
)


_RESCUEACK = _descriptor.Descriptor(
  name='RescueAck',
  full_name='RescueAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RescueAck.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='choice', full_name='RescueAck.choice', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESCUEACK_RESCUEACKCHOICE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=393,
)


_FROMMARS = _descriptor.Descriptor(
  name='FromMars',
  full_name='FromMars',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rescue_demand', full_name='FromMars.rescue_demand', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rescue_ack', full_name='FromMars.rescue_ack', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='FromMars.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=395,
  serialized_end=487,
)


_RESCUEOFFER = _descriptor.Descriptor(
  name='RescueOffer',
  full_name='RescueOffer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RescueOffer.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='RescueOffer.date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nb_places', full_name='RescueOffer.nb_places', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=554,
)


_FROMEARTH = _descriptor.Descriptor(
  name='FromEarth',
  full_name='FromEarth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rescue_offer', full_name='FromEarth.rescue_offer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='FromEarth.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=556,
  serialized_end=613,
)

_ASTRONAUT.fields_by_name['health_status'].enum_type = _ASTRONAUT_HEALTHSTATUS
_ASTRONAUT_HEALTHSTATUS.containing_type = _ASTRONAUT
_RESCUEDEMAND.fields_by_name['ask_before'].message_type = _DATE
_RESCUEDEMAND.fields_by_name['astronaut'].message_type = _ASTRONAUT
_RESCUEACK.fields_by_name['choice'].enum_type = _RESCUEACK_RESCUEACKCHOICE
_RESCUEACK_RESCUEACKCHOICE.containing_type = _RESCUEACK
_FROMMARS.fields_by_name['rescue_demand'].message_type = _RESCUEDEMAND
_FROMMARS.fields_by_name['rescue_ack'].message_type = _RESCUEACK
_FROMMARS.oneofs_by_name['type'].fields.append(
  _FROMMARS.fields_by_name['rescue_demand'])
_FROMMARS.fields_by_name['rescue_demand'].containing_oneof = _FROMMARS.oneofs_by_name['type']
_FROMMARS.oneofs_by_name['type'].fields.append(
  _FROMMARS.fields_by_name['rescue_ack'])
_FROMMARS.fields_by_name['rescue_ack'].containing_oneof = _FROMMARS.oneofs_by_name['type']
_RESCUEOFFER.fields_by_name['date'].message_type = _DATE
_FROMEARTH.fields_by_name['rescue_offer'].message_type = _RESCUEOFFER
_FROMEARTH.oneofs_by_name['type'].fields.append(
  _FROMEARTH.fields_by_name['rescue_offer'])
_FROMEARTH.fields_by_name['rescue_offer'].containing_oneof = _FROMEARTH.oneofs_by_name['type']
DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['Astronaut'] = _ASTRONAUT
DESCRIPTOR.message_types_by_name['RescueDemand'] = _RESCUEDEMAND
DESCRIPTOR.message_types_by_name['RescueAck'] = _RESCUEACK
DESCRIPTOR.message_types_by_name['FromMars'] = _FROMMARS
DESCRIPTOR.message_types_by_name['RescueOffer'] = _RESCUEOFFER
DESCRIPTOR.message_types_by_name['FromEarth'] = _FROMEARTH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), dict(
  DESCRIPTOR = _DATE,
  __module__ = 'earth_mars_pb2'
  # @@protoc_insertion_point(class_scope:Date)
  ))
_sym_db.RegisterMessage(Date)

Astronaut = _reflection.GeneratedProtocolMessageType('Astronaut', (_message.Message,), dict(
  DESCRIPTOR = _ASTRONAUT,
  __module__ = 'earth_mars_pb2'
  # @@protoc_insertion_point(class_scope:Astronaut)
  ))
_sym_db.RegisterMessage(Astronaut)

RescueDemand = _reflection.GeneratedProtocolMessageType('RescueDemand', (_message.Message,), dict(
  DESCRIPTOR = _RESCUEDEMAND,
  __module__ = 'earth_mars_pb2'
  # @@protoc_insertion_point(class_scope:RescueDemand)
  ))
_sym_db.RegisterMessage(RescueDemand)

RescueAck = _reflection.GeneratedProtocolMessageType('RescueAck', (_message.Message,), dict(
  DESCRIPTOR = _RESCUEACK,
  __module__ = 'earth_mars_pb2'
  # @@protoc_insertion_point(class_scope:RescueAck)
  ))
_sym_db.RegisterMessage(RescueAck)

FromMars = _reflection.GeneratedProtocolMessageType('FromMars', (_message.Message,), dict(
  DESCRIPTOR = _FROMMARS,
  __module__ = 'earth_mars_pb2'
  # @@protoc_insertion_point(class_scope:FromMars)
  ))
_sym_db.RegisterMessage(FromMars)

RescueOffer = _reflection.GeneratedProtocolMessageType('RescueOffer', (_message.Message,), dict(
  DESCRIPTOR = _RESCUEOFFER,
  __module__ = 'earth_mars_pb2'
  # @@protoc_insertion_point(class_scope:RescueOffer)
  ))
_sym_db.RegisterMessage(RescueOffer)

FromEarth = _reflection.GeneratedProtocolMessageType('FromEarth', (_message.Message,), dict(
  DESCRIPTOR = _FROMEARTH,
  __module__ = 'earth_mars_pb2'
  # @@protoc_insertion_point(class_scope:FromEarth)
  ))
_sym_db.RegisterMessage(FromEarth)


# @@protoc_insertion_point(module_scope)
