/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: survey.proto */

#ifndef PROTOBUF_C_survey_2eproto__INCLUDED
#define PROTOBUF_C_survey_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Survey Survey;


/* --- enums --- */

typedef enum _Gender {
  GENDER__FEMALE = 0,
  GENDER__MALE = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GENDER)
} Gender;

/* --- messages --- */

struct  _Survey
{
  ProtobufCMessage base;
  Gender gender;
  uint32_t size_in_cm;
};
#define SURVEY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&survey__descriptor) \
    , GENDER__FEMALE, 0 }


/* Survey methods */
void   survey__init
                     (Survey         *message);
size_t survey__get_packed_size
                     (const Survey   *message);
size_t survey__pack
                     (const Survey   *message,
                      uint8_t             *out);
size_t survey__pack_to_buffer
                     (const Survey   *message,
                      ProtobufCBuffer     *buffer);
Survey *
       survey__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   survey__free_unpacked
                     (Survey *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Survey_Closure)
                 (const Survey *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    gender__descriptor;
extern const ProtobufCMessageDescriptor survey__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_survey_2eproto__INCLUDED */
