#ifndef SOCKET_TCP_CONF_H
#define SOCKET_TCP_CONF_H

#define LOCALHOST_IPV4_ADDR "127.0.0.1"
#define LOCAL_IPV4_ADDR "192.168.122.2"
#define GIVER_IPV4_ADDR LOCALHOST_IPV4_ADDR
#define CHECKER_IPV4_ADDR LOCALHOST_IPV4_ADDR

#define GIVER_TCP_PORT 60000
#define CHECKER_TCP_PORT 60001

#define MAX_CLIENT 1


#endif /* SOCKET_TCP_CONF_H */
