/* survey.pb-c.c */

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: survey.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "survey.pb-c.h"
void   survey__init
                     (Survey         *message)
{
  static const Survey init_value = SURVEY__INIT;
  *message = init_value;
}
size_t survey__get_packed_size
                     (const Survey *message)
{
  assert(message->base.descriptor == &survey__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t survey__pack
                     (const Survey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &survey__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t survey__pack_to_buffer
                     (const Survey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &survey__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Survey *
       survey__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Survey *)
     protobuf_c_message_unpack (&survey__descriptor,
                                allocator, len, data);
}
void   survey__free_unpacked
                     (Survey *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &survey__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor survey__field_descriptors[2] =
{
  {
    "gender",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Survey, gender),
    &gender__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size_in_cm",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Survey, size_in_cm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned survey__field_indices_by_name[] = {
  0,   /* field[0] = gender */
  1,   /* field[1] = size_in_cm */
};
static const ProtobufCIntRange survey__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor survey__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Survey",
  "Survey",
  "Survey",
  "",
  sizeof(Survey),
  2,
  survey__field_descriptors,
  survey__field_indices_by_name,
  1,  survey__number_ranges,
  (ProtobufCMessageInit) survey__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue gender__enum_values_by_number[2] =
{
  { "FEMALE", "GENDER__FEMALE", 0 },
  { "MALE", "GENDER__MALE", 1 },
};
static const ProtobufCIntRange gender__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex gender__enum_values_by_name[2] =
{
  { "FEMALE", 0 },
  { "MALE", 1 },
};
const ProtobufCEnumDescriptor gender__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Gender",
  "Gender",
  "Gender",
  "",
  2,
  gender__enum_values_by_number,
  2,
  gender__enum_values_by_name,
  1,
  gender__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
