/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: olympic_games_registration.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "olympic_games_registration.pb-c.h"
void   date__init
                     (Date         *message)
{
  static const Date init_value = DATE__INIT;
  *message = init_value;
}
size_t date__get_packed_size
                     (const Date *message)
{
  assert(message->base.descriptor == &date__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t date__pack
                     (const Date *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &date__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t date__pack_to_buffer
                     (const Date *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &date__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Date *
       date__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Date *)
     protobuf_c_message_unpack (&date__descriptor,
                                allocator, len, data);
}
void   date__free_unpacked
                     (Date *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &date__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   start_time__init
                     (StartTime         *message)
{
  static const StartTime init_value = START_TIME__INIT;
  *message = init_value;
}
size_t start_time__get_packed_size
                     (const StartTime *message)
{
  assert(message->base.descriptor == &start_time__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t start_time__pack
                     (const StartTime *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &start_time__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t start_time__pack_to_buffer
                     (const StartTime *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &start_time__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartTime *
       start_time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartTime *)
     protobuf_c_message_unpack (&start_time__descriptor,
                                allocator, len, data);
}
void   start_time__free_unpacked
                     (StartTime *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &start_time__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   contest__init
                     (Contest         *message)
{
  static const Contest init_value = CONTEST__INIT;
  *message = init_value;
}
size_t contest__get_packed_size
                     (const Contest *message)
{
  assert(message->base.descriptor == &contest__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t contest__pack
                     (const Contest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &contest__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t contest__pack_to_buffer
                     (const Contest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &contest__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Contest *
       contest__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Contest *)
     protobuf_c_message_unpack (&contest__descriptor,
                                allocator, len, data);
}
void   contest__free_unpacked
                     (Contest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &contest__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   registration__init
                     (Registration         *message)
{
  static const Registration init_value = REGISTRATION__INIT;
  *message = init_value;
}
size_t registration__get_packed_size
                     (const Registration *message)
{
  assert(message->base.descriptor == &registration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t registration__pack
                     (const Registration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &registration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t registration__pack_to_buffer
                     (const Registration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &registration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Registration *
       registration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Registration *)
     protobuf_c_message_unpack (&registration__descriptor,
                                allocator, len, data);
}
void   registration__free_unpacked
                     (Registration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &registration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   competitor__init
                     (Competitor         *message)
{
  static const Competitor init_value = COMPETITOR__INIT;
  *message = init_value;
}
size_t competitor__get_packed_size
                     (const Competitor *message)
{
  assert(message->base.descriptor == &competitor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t competitor__pack
                     (const Competitor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &competitor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t competitor__pack_to_buffer
                     (const Competitor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &competitor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Competitor *
       competitor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Competitor *)
     protobuf_c_message_unpack (&competitor__descriptor,
                                allocator, len, data);
}
void   competitor__free_unpacked
                     (Competitor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &competitor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor date__field_descriptors[3] =
{
  {
    "year",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Date, year),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "month",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Date, month),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "day",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Date, day),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned date__field_indices_by_name[] = {
  2,   /* field[2] = day */
  1,   /* field[1] = month */
  0,   /* field[0] = year */
};
static const ProtobufCIntRange date__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor date__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Date",
  "Date",
  "Date",
  "",
  sizeof(Date),
  3,
  date__field_descriptors,
  date__field_indices_by_name,
  1,  date__number_ranges,
  (ProtobufCMessageInit) date__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor start_time__field_descriptors[2] =
{
  {
    "hour",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartTime, hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minute",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartTime, minute),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_time__field_indices_by_name[] = {
  0,   /* field[0] = hour */
  1,   /* field[1] = minute */
};
static const ProtobufCIntRange start_time__number_ranges[1 + 1] =
{
  { 4, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor start_time__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StartTime",
  "StartTime",
  "StartTime",
  "",
  sizeof(StartTime),
  2,
  start_time__field_descriptors,
  start_time__field_indices_by_name,
  1,  start_time__number_ranges,
  (ProtobufCMessageInit) start_time__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor contest__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "date",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Contest, date),
    &date__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_time",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Contest, start_time),
    &start_time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned contest__field_indices_by_name[] = {
  1,   /* field[1] = date */
  0,   /* field[0] = name */
  2,   /* field[2] = start_time */
};
static const ProtobufCIntRange contest__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor contest__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Contest",
  "Contest",
  "Contest",
  "",
  sizeof(Contest),
  3,
  contest__field_descriptors,
  contest__field_indices_by_name,
  1,  contest__number_ranges,
  (ProtobufCMessageInit) contest__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor registration__field_descriptors[2] =
{
  {
    "bib_number",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Registration, bib_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contest",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Registration, n_contest),
    offsetof(Registration, contest),
    &contest__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned registration__field_indices_by_name[] = {
  0,   /* field[0] = bib_number */
  1,   /* field[1] = contest */
};
static const ProtobufCIntRange registration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor registration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Registration",
  "Registration",
  "Registration",
  "",
  sizeof(Registration),
  2,
  registration__field_descriptors,
  registration__field_indices_by_name,
  1,  registration__number_ranges,
  (ProtobufCMessageInit) registration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor competitor__field_descriptors[3] =
{
  {
    "lastname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Competitor, lastname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firstname",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Competitor, firstname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "birth_date",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Competitor, birth_date),
    &date__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned competitor__field_indices_by_name[] = {
  2,   /* field[2] = birth_date */
  1,   /* field[1] = firstname */
  0,   /* field[0] = lastname */
};
static const ProtobufCIntRange competitor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor competitor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Competitor",
  "Competitor",
  "Competitor",
  "",
  sizeof(Competitor),
  3,
  competitor__field_descriptors,
  competitor__field_indices_by_name,
  1,  competitor__number_ranges,
  (ProtobufCMessageInit) competitor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
